### ISSUE TITLE
add environment setup to README

### ISSUE THREAD

**Issue by agladstein** [andrewkern/analysis#2]
Can you add environment setup instructions?

What needs to be installed?

I was going to test it out (i.e. try to break it), but then I realized I don't know what's needed to run it.

**Comment by andrewkern** [comment]
I added a `requirements.txt` file that should cover it.

**Comment by agladstein** [comment]
Seriously?! 
Of course it couldn't be easy...

I started a brand new virtual machine with nothing on it...
```
pip install -r requirements
```

And got this:
```
Collecting msprime (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/51/bc/cd0d661ae86c36b1360c6863eecef7483561d37024e61c5d4b131b6c7a80/msprime-0.7.0.tar.gz (449kB)
    100% |████████████████████████████████| 450kB 1.7MB/s
Collecting scikit-allel (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/a4/8b/65bbb9c597386cdf139f476b3582c69c2c635c08cb83da7c1decd0491d9d/scikit-allel-1.2.0.tar.gz (10.8MB)
    100% |████████████████████████████████| 10.8MB 116kB/s
Collecting snakemake (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/7b/e0/af241f6a43f245adf701524512920bebc6097290eda7ac9dd6587d65a925/snakemake-5.4.2.tar.gz (171kB)
    100% |████████████████████████████████| 174kB 4.0MB/s
Collecting parallel (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/31/5b/66966fb4d103191b7cbc92730db6a335986fbdb3d9f55cbb54b7ba87e9d4/parallel-0.2.5.tar.gz (57kB)
    100% |████████████████████████████████| 61kB 4.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xvljoyu5/parallel/setup.py", line 5, in <module>
        import pprocess
      File "/tmp/pip-build-xvljoyu5/parallel/pprocess.py", line 255
        raise AcknowledgementError, obj
                                  ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xvljoyu5/parallel/
```

Sad... I'll deal with it. For some reason I was just hoping for once packages would install without a problem.

**Comment by andrewkern** [comment]
ugh parallel is failing?!? I installed that at the system level on our server using `sudo apt-get install parallel` I believe

**Comment by agladstein** [comment]
That makes sense.
Is that gnu parallel?

If that's the case, then I don't think it makes sense to include it in the requirements.txt, does it?

**Comment by andrewkern** [comment]
yes gnu parallel. I'm agnostic as to whether it should go in `requirements.txt` but it's not standard on most linux distros I believe.

**Comment by agladstein** [comment]
If the `requirements.txt` is going to be used with `pip` like I did, then I think it will always break.

**Comment by andrewkern** [comment]
got it. we will need to define that as a dependency some other way or move away from using parallel. those threads could easily be farmed out to cluster nodes instead.

**Comment by agladstein** [comment]
Oh man.... I did a `sudo apt-get install parallel` and removed it from the `requirements.txt` and now more things are breaking in the `pip install -r requirements.txt`...

**Comment by agladstein** [comment]
That's it...
I'm using Docker. That will take care of defining the dependencies.

**Comment by agladstein** [comment]
I seemingly have installed things without any errors.

Changed the `requirements.txt` to
```
setuptools
msprime
scikit-allel
snakemake
```

Then did,
```
sudo apt-get install parallel
sudo apt-get install build-essential
sudo apt-get install libgsl-dev
sudo apt-get clean
pip3 install -r requirements.txt
```

**Comment by agladstein** [comment]
So... actually, I set up a virtualenv and then pip installed.

```
sudo apt-get install parallel
sudo apt-get install build-essential
sudo apt-get install libgsl-dev
sudo apt install virtualenv
sudo apt-get clean
virtualenv -p python3 .venv
source .venv/bin/activate
pip3 install -r requirements.txt
```

But... clearly missing all the `dadi` dependencies.

```
Traceback (most recent call last):
  File "GutenkunstThreePopOutOfAfrica.py", line 10, in <module>
    import stdpopsim
ModuleNotFoundError: No module named 'stdpopsim'
[Thu Mar  7 02:52:20 2019]
Error in rule simulation:
    jobid: 1
    output: G3OOA.trees

RuleException:
CalledProcessError in line 11 of /home/ubuntu/analysis/n_t/Snakefile:
Command 'set -euo pipefail;  python GutenkunstThreePopOutOfAfrica.py' returned non-zero exit status 1.
  File "/home/ubuntu/analysis/n_t/Snakefile", line 11, in __rule_simulation
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ubuntu/analysis/n_t/.snakemake/log/2019-03-07T025220.273738.snakemake.log
```

Ugh...
I will definitely make a Dockerfile for this once I getting my env sorted.

But, on the upside - that's a clear error message.

**Comment by andrewkern** [comment]
Ah we need to require stdpopsim. That will involve a git clone and then an install. Sorry about that.

**Comment by agladstein** [comment]
That's why I'm testing it for you hahaha

Is that regular dadi? Or does it need to come from someplace else special?

**Comment by andrewkern** [comment]
No dadi- that’s the code we wrote for the stdpopsim human model

**Comment by agladstein** [comment]
Oh right. I saw Gutenkunst + import errors and my brain automatically jumped to dadi haha

I'll try that later today...

**Comment by agladstein** [comment]
Where do I need to git clone and how do I install?

Now, when I run `snakemake` I get the error:
```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       simulation
        1       stairwayplot
        3

[Fri Mar  8 01:05:52 2019]
rule simulation:
    output: G3OOA.trees
    jobid: 1

/bin/bash: python: command not found
[Fri Mar  8 01:05:52 2019]
Error in rule simulation:
    jobid: 1
    output: G3OOA.trees

RuleException:
CalledProcessError in line 11 of /home/ubuntu/stdpopsim/analysis/n_t/Snakefile:
Command 'set -euo pipefail;  python GutenkunstThreePopOutOfAfrica.py' returned non-zero exit status 127.
  File "/home/ubuntu/stdpopsim/analysis/n_t/Snakefile", line 11, in __rule_simulation
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ubuntu/stdpopsim/analysis/n_t/.snakemake/log/2019-03-08T010552.789745.snakemake.log
```

Then, if I try just `python GutenkunstThreePopOutOfAfrica.py`, I get the error:
```
Traceback (most recent call last):
  File "GutenkunstThreePopOutOfAfrica.py", line 8, in <module>
    from stdpopsim import homo_sapiens
ModuleNotFoundError: No module named 'stdpopsim'
```

I tested:
```
$ git clone https://github.com/popgensims/stdpopsim.git
$ cd stdpopsim
$ git clone https://github.com/andrewkern/analysis.git
$ cd analysis/n_t
$ python
>>> import stdpopsim
```
And that doesn't work.

I also tried:
```
$ git clone https://github.com/andrewkern/analysis.git
$ cd analysis/n_t
$ git clone https://github.com/popgensims/stdpopsim.git
$ python
>>> import stdpopsim
```
And that works.

but, 
```
>>> from stdpopsim import homo_sapiens
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'homo_sapiens'
```

**Comment by agladstein** [comment]
How exactly is your directory structure setup for `analysis` and `stdpopsim`?

Because I tried the two tests I did above and it's still not importing `from stdpopsim import homo_sapiens`.

**Comment by andrewkern** [comment]
i think the issue is that you haven't installed `stdpopsim`. Again we need to add documentation (I'll try to get on that this morning) but once you have cloned `stdpopsim` invoke `python setup.py install` and it will put the module into your python path. then it should be available for import.

**Comment by agladstein** [comment]
I got the env to work! woohoo!

Install dependencies
```
sudo apt install default-jre
sudo apt-get install parallel
sudo apt-get install build-essential
sudo apt-get install libgsl-dev
sudo apt install python3-pip
sudo apt install virtualenv
sudo apt-get clean
```

I needed to change the `requirements.txt` to 
```
setuptools
msprime
scikit-allel
snakemake
matplotlib
pandas
```

Install analysis packages
```
git clone https://github.com/andrewkern/analysis.git
cd analysis
pip3 install -r requirements.txt
```

Install stdpopsim packages
```
git clone https://github.com/popgensims/stdpopsim.git
cd stdpopsim
sudo python setup.py install
```

Now, in analysis/n_t `from stdpopsim import homo_sapiens` works.
But, `snakemake` is not in the proper python path

Set up virtualenv so snakemake is in path?
```
virtualenv -p python3 ~/.venv
source ~/.venv/bin/activate
cd analysis
pip3 install -r requirements.txt
```

run pipeline
```
cd n_t
snakemake
```

Like @jeromekelleher said, we can nail down dealing with dependencies later. But, have this here as notes for later.

**Comment by agladstein** [comment]
I followed my directions from earlier (on Ubuntu 18.04 vm):

```
sudo apt install default-jre
sudo apt-get install parallel
sudo apt-get install build-essential
sudo apt-get install libgsl-dev
sudo apt install python3-pip
sudo apt install virtualenv
sudo apt-get clean

cd ~
git clone https://github.com/andrewkern/analysis.git
pip3 install -r requirements.txt
```

But, the vm didn't already have anaconda, so I installed it:
```
cd /tmp
curl -O https://repo.anaconda.com/archive/Anaconda3-2018.12-Linux-x86_64.sh
bash Anaconda3-2018.12-Linux-x86_64.sh
source ~/.bashrc
```

This includes `pip`
```
ubuntu@gradually-on-catfish:~/analysis$ which pip
/home/ubuntu/anaconda3/bin/pip
```

When I had `pip3 install -r requirements.txt` before installing anaconda, it installed the packages to the "wrong" Python environment.

I did `pip install -r requirements.txt` after installing anaconda and got this error (not including entire traceback):
```
...
  Running setup.py clean for datrie
Failed to build datrie
Installing collected packages: smmap2, gitdb2, gitpython, datrie, snakemake
  Running setup.py install for datrie ... error
    Complete output from command /home/ubuntu/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9y9iij_u/dat
rie/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))
" install --record /tmp/pip-record-1jikmxkb/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_clib
    building 'libdatrie' library
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/libdatrie
    creating build/temp.linux-x86_64-3.7/libdatrie/datrie
    gcc -pthread -B /home/ubuntu/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -
fPIC -Ilibdatrie -c libdatrie/datrie/tail.c -o build/temp.linux-x86_64-3.7/libdatrie/datrie/tail.o
....
....
    src/datrie.c:24942:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
         tstate->exc_traceback = *tb;
                 ^~~~~~~~~~~~~
                 curexc_traceback
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/home/ubuntu/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9y9iij_u/datrie/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1jikmxkb/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-9y9iij_u/datrie/
```

**Comment by jeromekelleher** [comment]
If we're using conda we should install msprime (and everything else, ideally) via conda, using pip only as a last resort when conda packages don't exist. We shouldn't need to install anything other than  ``default-jre`` and ``build-essential`` via apt (possibily we don't even need build-essential, as conda uses its own compilers AFAIK).

I think it's fine requiring conda here, as bioconda takes a lot of pain out of installing bioinf tools.

**Comment by agladstein** [comment]
@jeromekelleher Is that with full on anaconda or do you think miniconda will be sufficient?

Yeah, when i was watching anaconda install it looked like it was including a lot of the things I had `apt-get install` previously.

**Comment by agladstein** [comment]
I'm starting from a miniconda Docker image so I don't have wipe my system and reinstall anaconda every time it doesn't work.

Pull and Run miniconda Docker Image
```
sudo docker run -i -t continuumio/miniconda3:4.3.11 /bin/bash
```

From inside miniconda Docker container install dependencies
```
apt-get update
apt-get install build-essential
apt-get install default-jre
```

From inside miniconda Docker container install python packages
```
conda install anaconda-client
conda install -c terhorst -c bioconda smcpp
conda install -c conda-forge scikit-allel
```
looks like `msprime` is already installed with `smcpp`.
But `tskit` isn't installed. Should I install `msprime` again or just install `tskit`?

**Comment by andrewkern** [comment]
I’m going to guess based on our experiences on Friday that you now have an older version of msprime install ( prob v0.5) and that things won’t run without rerunning conda install msprime -c conda-forge

**Comment by agladstein** [comment]
Now I'm getting an error that looks like it's coming from java??

Pull and Run miniconda Docker Image
```
sudo docker run -i -t continuumio/miniconda3:4.3.11 /bin/bash
```

From inside miniconda Docker container install dependencies
```
apt-get update
apt-get install build-essential
apt-get install default-jre
```

From inside miniconda Docker container clone repo
```
git clone https://github.com/andrewkern/analysis.git
cd analysis
```

From inside miniconda Docker container install python packages
```
conda install anaconda-client
conda install -c terhorst -c bioconda smcpp
conda install -c conda-forge scikit-allel
conda install -c bioconda -c conda-forge snakemake
conda install msprime -c conda-forge
```


From inside miniconda Docker container clone stdpopsim repo
```
git clone https://github.com/popgensims/stdpopsim.git
cd stdpopsim
python setup.py install
```

Run snakemake pipeline
```
cd ../n_t
```

```
root@ea4b31efbebc:/analysis/n_t# snakemake -j 7
/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `n
p.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 7
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        2       homo_sapiens_Gutenkunst_simulation
        2       homo_sapiens_Gutenkunst_stairwayplot
        2       homo_sapiens_Gutenkunst_stairwayplot_plot
        1       homo_sapiens_compound_stairwayplot
        1       sp_download
        9

[Mon Mar 18 01:52:44 2019]
Job 7: downloading stairwayplot


[Mon Mar 18 01:52:44 2019]
rule homo_sapiens_Gutenkunst_simulation:
    output: homo_sapiens_Gutenkunst/1845187043.chr22.trees
    jobid: 6
    wildcards: seeds=1845187043, chrms=chr22

[Mon Mar 18 01:52:44 2019]
rule homo_sapiens_Gutenkunst_simulation:
    output: homo_sapiens_Gutenkunst/1675701734.chr22.trees
    jobid: 8
    wildcards: seeds=1675701734, chrms=chr22

--2019-03-18 01:52:44--  http://sesame.uoregon.edu/~adkern/stdpopsim/stairwayplot.tar.gz
Resolving sesame.uoregon.edu (sesame.uoregon.edu)... 184.171.122.115
Connecting to sesame.uoregon.edu (sesame.uoregon.edu)|184.171.122.115|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 959033 (937K) [application/x-gzip]
Saving to: ‘stairwayplot.tar.gz’

stairwayplot.tar.gz                 100%[==================================================================>] 936.56K  4.70MB/s   in 0.2s

2019-03-18 01:52:44 (4.70 MB/s) - ‘stairwayplot.tar.gz’ saved [959033/959033]

[Mon Mar 18 01:52:44 2019]
Finished job 7.
1 of 9 steps (11%) done
/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Job counts:
        count   jobs
        1       homo_sapiens_Gutenkunst_simulation
        1
/opt/conda/lib/python3.6/site-packages/stdpopsim-0.1.dev66+g0add546-py3.6.egg/stdpopsim/genomes.py:76: UserWarning: Warning: recombination map not found for chromosome: 'chr22' on map: 'HapmapII_GRCh37', substituting a zero-recombination map.
Job counts:
        count   jobs
        1       homo_sapiens_Gutenkunst_simulation
        1
/opt/conda/lib/python3.6/site-packages/stdpopsim-0.1.dev66+g0add546-py3.6.egg/stdpopsim/genomes.py:76: UserWarning: Warning: recombination ma
p not found for chromosome: 'chr22' on map: 'HapmapII_GRCh37', substituting a zero-recombination map.
[Mon Mar 18 01:52:45 2019]
Finished job 6.
2 of 9 steps (22%) done
[Mon Mar 18 01:52:45 2019]
Finished job 8.
3 of 9 steps (33%) done

[Mon Mar 18 01:52:45 2019]
rule homo_sapiens_Gutenkunst_stairwayplot:
    input: homo_sapiens_Gutenkunst/1845187043.chr22.trees, stairwayplot/swarmops.jar
    output: homo_sapiens_Gutenkunst/1845187043.chr22.estimated_Ne.txt
    jobid: 4
    wildcards: seeds=1845187043, chrms=chr22
    threads: 7

/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Job counts:
        count   jobs
        1       homo_sapiens_Gutenkunst_stairwayplot
        1
  0%|                                                                                                                 | 0/11 [00:00<?, ?it/s]Exception in thread "main" java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
        at Stairway_plot_theta_estimation02.main(Stairway_plot_theta_estimation02.java:69)
Exception in thread "main" java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
        at Stairway_plot_theta_estimation02.main(Stairway_plot_theta_estimation02.java:69)
Exception in thread "main" java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
        at Stairway_plot_theta_estimation02.main(Stairway_plot_theta_estimation02.java:69)
  9%|█████████▌                                                                                               | 1/11 [00:00<00:01,  9.38it/s]
java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
        at Stairway_plot_theta_estimation02.main(Stairway_plot_theta_estimation02.java:69)
Exception in thread "main" java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
        at Stairway_plot_theta_estimation02.main(Stairway_plot_theta_estimation02.java:69)
Exception in thread "main" java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
        at Stairway_plot_theta_estimation02.main(Stairway_plot_theta_estimation02.java:69)
Exception in thread "main" java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
        at Stairway_plot_theta_estimation02.main(Stairway_plot_theta_estimation02.java:69)
Exception in thread "main" Exception in thread "main" java.util.NoSuchElementException
java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)

        at Stairway_plot_theta_estimation02.main(Stairway_plot_theta_estimation02.java:69)      at Stairway_plot_theta_estimation02.main(Stairway_plot_theta_estimation02.java:69)

 73%|████████████████████████████████████████████████████████████████████████████▎                            | 8/11 [00:00<00:00, 12.59it/s]Exception in thread "main" java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
        at Stairway_plot_theta_estimation02.main(Stairway_plot_theta_estimation02.java:69)
Exception in thread "main" java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
        at Stairway_plot_theta_estimation02.main(Stairway_plot_theta_estimation02.java:69)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 44.37it/s]
nrep=11
1       sfs_0.txt.addTheta
Exception in thread "main" java.lang.NullPointerException
        at Stairway_plot_output_summary_commandline.main(Stairway_plot_output_summary_commandline.java:70)
[Mon Mar 18 01:52:47 2019]
INFO:snakemake.logging:[Mon Mar 18 01:52:47 2019]
Error in rule homo_sapiens_Gutenkunst_stairwayplot:
ERROR:snakemake.logging:Error in rule homo_sapiens_Gutenkunst_stairwayplot:
    jobid: 0
ERROR:snakemake.logging:    jobid: 0
    output: homo_sapiens_Gutenkunst/1845187043.chr22.estimated_Ne.txt
ERROR:snakemake.logging:    output: homo_sapiens_Gutenkunst/1845187043.chr22.estimated_Ne.txt

ERROR:snakemake.logging:
RuleException:
CalledProcessError in line 53 of /analysis/n_t/Snakefile:
Command 'java -cp /analysis/n_t/stairwayplot:/analysis/n_t/stairwayplot/swarmops.jar Stairway_plot_output_summary_commandline /tmp/tmpj2vvll8z 1e-08 10 homo_sapiens_Gutenkunst/1845187043.chr22.estimated_Ne.txt' returned non-zero exit status 1.
  File "/analysis/n_t/Snakefile", line 53, in __rule_homo_sapiens_Gutenkunst_stairwayplot
  File "/analysis/n_t/stairway.py", line 113, in run_summary
  File "/opt/conda/lib/python3.6/subprocess.py", line 438, in run
  File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
ERROR:snakemake.logging:RuleException:
CalledProcessError in line 53 of /analysis/n_t/Snakefile:
Command 'java -cp /analysis/n_t/stairwayplot:/analysis/n_t/stairwayplot/swarmops.jar Stairway_plot_output_summary_commandline /tmp/tmpj2vvll8z 1e-08 10 homo_sapiens_Gutenkunst/1845187043.chr22.estimated_Ne.txt' returned non-zero exit status 1.
  File "/analysis/n_t/Snakefile", line 53, in __rule_homo_sapiens_Gutenkunst_stairwayplot
  File "/analysis/n_t/stairway.py", line 113, in run_summary
  File "/opt/conda/lib/python3.6/subprocess.py", line 438, in run
  File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
ERROR:snakemake.logging:Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /analysis/n_t/.snakemake/log/2019-03-18T015242.220215.snakemake.log
```  

two additional notes:
- If I do `pip install -r requirements.txt` instead of using `conda` to install the other packages, I get the same error.
- If I do the `conda install` in a different order from what I have here it breaks - I think because the versions of dependencies gets messed up.

**Comment by jeromekelleher** [comment]
A couple of things occur to me here:

1. Where is smcpp pulling msprime in from? I guess it's from bioconda, so it's really old. Does it actually use msprime for the code we're using? If so, we're going to have to set up a separate conda env for running smc++.
2. The Java exception that you're seeing *might* be as a result of us substituting a zero recombination map, from a bug we recently introduced in stdpopsim (https://github.com/popgensims/stdpopsim/issues/38)

**Comment by agladstein** [comment]
I will wait until https://github.com/popgensims/stdpopsim/issues/38 is resolved and then I will try again.

**Comment by andrewkern** [comment]
> A couple of things occur to me here:
> 
>     1. Where is smcpp pulling msprime in from? I guess it's from bioconda, so it's really old. Does it actually use msprime for the code we're using? If so, we're going to have to set up a separate conda env for running smc++.
> 
on my system smcpp was pulling msprime from terhorst's channel, which was strange. i was able to fix it by calling `conda install msprime -c conda-forge` after install of smcpp. it should be simple enough to set the channel priorities such that conda-forge > bioconda > terhost in a .condarc file and then I think the install using conda should work?

**Comment by andrewkern** [comment]
> > A couple of things occur to me here:
> > ```
> > 1. Where is smcpp pulling msprime in from? I guess it's from bioconda, so it's really old. Does it actually use msprime for the code we're using? If so, we're going to have to set up a separate conda env for running smc++.
> > ```
> 
> on my system smcpp was pulling msprime from terhorst's channel, which was strange. i was able to fix it by calling `conda install msprime -c conda-forge` after install of smcpp. it should be simple enough to set the channel priorities such that conda-forge > bioconda > terhost in a .condarc file and then I think the install using conda should work?

So @jgallowa07 tried this today and it didn't work 😢. still working on a better way to get `smcpp` installed without messing up the msprime install.

**Comment by agladstein** [comment]
It seems to me like dependencies are getting complicated enough at this point that the only sane way to get this working for people is to provide a docker image.
And if it comes down to it we can have a separate python env for smcpp in the image.

I think figure out the cleanest way to install everything and provide instructions, but include a docker image for people who want to avoid the struggle 😄

**Comment by jeromekelleher** [comment]
Sounds like a plan @agladstein. FWIW, I think the only reasonable way to go forward is to give smc++ its own conda env (maybe using [conda execute](https://github.com/conda-tools/conda-execute)?). It's too finicky otherwise.

**Comment by andrewkern** [comment]
okay folks here is a very simple way to get all the current requirements into a conda environment. i've done this on two machines now without issue.

```
conda create -n popsim_env_test python=3.6.8 --yes
conda activate popsim_env_test

git clone https://github.com/andrewkern/analysis.git
cd analysis/
git checkout remotes/origin/smcpp

for c in terhorst bioconda defaults conda-forge; do conda config --add channels $c; done
conda install --file requirements.txt --yes
```

note I'm switching to the smcpp branch because I have an edited `requirements.txt` there

@agladstein @jgallowa07 can you confirm this? the key seems to be pinning down the msprime version in `requirements.txt`


now there is a new bug that I have to fix in `analysis/n_t/simulations.py` that was induced by the change to `default_mutation_rate` from this [PR](https://github.com/popgensims/stdpopsim/pull/34#issuecomment-474515598). I'll do this in a separate PR.

**Comment by agladstein** [comment]
wooh!
I will double check! 🤞🤞

**Comment by andrewkern** [comment]
Hey @agladstein- any confirmation on this? I’d like to merge the PR that brings this in

**Comment by agladstein** [comment]
@andrewkern Sorry for the holdup! I'll work on it this evening!

**Comment by agladstein** [comment]
Ok, I believe I'm getting the expected error.
I also doubled checked that all the imports in the code imported in python console in the conda env. And they did!

So, I think you are good on the dependencies.

Could you add the exact instructions for how to install dependencies (and create the conda env) in the README?

I had to change two things for the installation:
```
sudo docker run -i -t continuumio/miniconda3:4.3.11 /bin/bash

conda install anaconda-client #<------- Had to add this
conda create -n popsim_env_test python=3.6.8 --yes
source activate popsim_env_test #<------ Had to change from conda to source

git clone https://github.com/andrewkern/analysis.git
git checkout remotes/origin/smcpp
for c in terhorst bioconda defaults conda-forge; do conda config --add channels $c; done
conda install --file requirements.txt --yes

git clone https://github.com/popgensims/stdpopsim.git
cd stdpopsim
python setup.py install

cd ../n_t
```

This was my `snakemake` output:
```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 7
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       download_genetic_map
        2       homo_sapiens_Gutenkunst_simulation
        2       homo_sapiens_Gutenkunst_stairwayplot
        2       homo_sapiens_Gutenkunst_stairwayplot_plot
        1       homo_sapiens_all_plot
        1       homo_sapiens_compound_smcpp
        1       homo_sapiens_compound_stairwayplot
        2       homo_sapiens_smcpp
        2       homo_sapiens_smcpp_plot
        1       sp_download
        16

[Sat Mar 23 00:09:46 2019]
Job 13: downloading stairwayplot



[Sat Mar 23 00:09:46 2019]
Job 15: Downloading default genetic map

--2019-03-23 00:09:46--  http://sesame.uoregon.edu/~adkern/stdpopsim/stairwayplot.tar.gz
Resolving sesame.uoregon.edu (sesame.uoregon.edu)... 184.171.122.115
Connecting to sesame.uoregon.edu (sesame.uoregon.edu)|184.171.122.115|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 959033 (937K) [application/x-gzip]
Saving to: ‘stairwayplot.tar.gz’

stairwayplot.tar.gz             100%[========================================================>] 936.56K  2.42MB/s   in 0.4s

2019-03-23 00:09:47 (2.42 MB/s) - ‘stairwayplot.tar.gz’ saved [959033/959033]

[Sat Mar 23 00:09:47 2019]
Finished job 13.
1 of 16 steps (6%) done
Job counts:
        count   jobs
        1       download_genetic_map
        1
[Sat Mar 23 00:09:53 2019]
Finished job 15.
2 of 16 steps (12%) done

[Sat Mar 23 00:09:53 2019]
rule homo_sapiens_Gutenkunst_simulation:
    input: .genetic_map_downloaded
    output: homo_sapiens_Gutenkunst/1845187043.chr22.trees
    jobid: 12
    wildcards: seeds=1845187043, chrms=chr22

[Sat Mar 23 00:09:53 2019]
rule homo_sapiens_Gutenkunst_simulation:
    input: .genetic_map_downloaded
    output: homo_sapiens_Gutenkunst/1675701734.chr22.trees
    jobid: 14
    wildcards: seeds=1675701734, chrms=chr22

Job counts:
        count   jobs
        1       homo_sapiens_Gutenkunst_simulation
        1
[Sat Mar 23 00:09:55 2019]
Error in rule homo_sapiens_Gutenkunst_simulation:
    jobid: 0
    output: homo_sapiens_Gutenkunst/1675701734.chr22.trees

RuleException:
AttributeError in line 59 of /analysis/n_t/Snakefile:
'Chromosome' object has no attribute 'mean_mutation_rate'
  File "/analysis/n_t/Snakefile", line 59, in __rule_homo_sapiens_Gutenkunst_simulation
  File "/analysis/n_t/simulations.py", line 20, in homo_sapiens_Gutenkunst
  File "/opt/conda/envs/popsim_env_test/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
Job counts:
        count   jobs
        1       homo_sapiens_Gutenkunst_simulation
        1
[Sat Mar 23 00:09:55 2019]
Error in rule homo_sapiens_Gutenkunst_simulation:
    jobid: 0
    output: homo_sapiens_Gutenkunst/1845187043.chr22.trees

RuleException:
AttributeError in line 59 of /analysis/n_t/Snakefile:
'Chromosome' object has no attribute 'mean_mutation_rate'
  File "/analysis/n_t/Snakefile", line 59, in __rule_homo_sapiens_Gutenkunst_simulation
  File "/analysis/n_t/simulations.py", line 20, in homo_sapiens_Gutenkunst
  File "/opt/conda/envs/popsim_env_test/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /analysis/n_t/.snakemake/log/2019-03-23T000944.978428.snakemake.log
```

**Comment by andrewkern** [comment]
Woot! Will do
